// tslint:disable
/**
 * OrgBook BC API
 * OrgBook BC is a public, searchable directory of digital records for registered businesses in the Province of British Columbia. Over time, other government organizations and businesses will also begin to issue digital records through OrgBook BC. For example, permits and licenses issued by various government services.
 *
 * The version of the OpenAPI document: v2
 * Contact: bcdevexchange@gov.bc.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
